"use client";

import { ArrowRight, CircleDollarSign, Clock3, Computer, Earth, LockKeyhole, Mail, MapPin, MessageCircle, Phone, Send, Users, Wifi, X, Zap } from "lucide-react";

export function Landing({ onSignIn }: { onSignIn: () => void }) {
  return <main className="landing">
    <nav className="landing-nav"><div className="landing-brand"><span><Computer size={20} /></span><b>NETCAFE</b></div><button className="nav-enter" onClick={onSignIn}>Sign in <ArrowRight size={17} /></button></nav>
    <section className="hero"><div className="eyebrow"><span /> SMART INTERNET CAFE MANAGEMENT</div><h1>Run your cafe.<br /><em>Stay in control.</em></h1><p>A focused command center for stations, customers, sessions, and every peso your internet cafe earns.</p><div className="hero-actions"><button onClick={onSignIn}>Open NetCafe Manager <ArrowRight size={18} /></button><a href="#features">Explore features</a></div><div className="hero-screen"><div className="screen-top"><span /><span /><span /><b>NETCAFE / LIVE OVERVIEW</b><i>● Online</i></div><div className="screen-content"><div className="screen-copy"><small>LIVE STATUS</small><strong>Everything is running smoothly.</strong><p>2 stations online · 1 active session</p></div><div className="mini-metrics"><div><Computer /><b>02</b><small>Stations</small></div><div><Clock3 /><b>01</b><small>Session</small></div><div><CircleDollarSign /><b>₱12.47</b><small>Today</small></div></div></div><div className="screen-line"><i /><i /><i /><i /><i /><i /></div></div></section>
    <section className="feature-strip" id="features"><div><Computer /><span><b>Station control</b><small>Manage every PC in one view</small></span></div><div><Users /><span><b>Customer flow</b><small>Approve and track accounts</small></span></div><div><Zap /><span><b>Simple billing</b><small>Clear session totals, instantly</small></span></div><div><Wifi /><span><b>Live updates</b><small>Always know what is happening</small></span></div></section>
    <section className="contact-section" id="contact"><div className="contact-heading"><span className="eyebrow"><span /> GET IN TOUCH</span><h2>Need help with your cafe?</h2><p>Our support team is ready to help you keep every station running smoothly.</p></div><div className="contact-grid"><a href="tel:+639171234567" className="contact-card"><Phone /><span><small>CALL US</small><b>+63 917 123 4567</b><em>Mon–Sat, 8:00 AM–8:00 PM</em></span></a><a href="mailto:support@netcafe.ph" className="contact-card"><Mail /><span><small>EMAIL SUPPORT</small><b>support@netcafe.ph</b><em>We reply within one business day</em></span></a><div className="contact-card"><MapPin /><span><small>VISIT US</small><b>Serving cafes across the Philippines</b><em>Remote setup and on-site support</em></span></div></div><div className="contact-cta"><div><b>Ready to simplify your operations?</b><span>Sign in to manage your stations, sessions, and staff.</span></div><button onClick={onSignIn}>Open manager <ArrowRight size={17} /></button></div></section>
    <footer className="landing-footer"><div className="footer-main"><div className="footer-brand"><div className="landing-brand"><span><Computer size={20} /></span><b>NETCAFE</b></div><p>Simple, dependable tools for modern internet cafes.</p><div className="social-links"><a href="#contact" aria-label="Chat support"><MessageCircle size={17} /></a><a href="#contact" aria-label="Website"><Earth size={17} /></a><a href="mailto:support@netcafe.ph" aria-label="Email"><Send size={16} /></a></div></div><div><b>Platform</b><a href="#features">Features</a><button onClick={onSignIn}>Sign in</button></div><div><b>Support</b><a href="#contact">Contact us</a><a href="mailto:support@netcafe.ph">Email support</a><a href="tel:+639171234567">Call support</a></div><div><b>Hours</b><span>Monday – Saturday</span><span>8:00 AM – 8:00 PM</span><span>Philippine time</span></div></div><div className="footer-bottom"><span>© 2026 NETCAFE MANAGER. ALL RIGHTS RESERVED.</span><span>Built for modern internet cafes</span></div></footer>
  </main>;
}

export function SignIn({ onClose, onSubmit, error }: { onClose: () => void; onSubmit: (email: string, password: string) => void; error: string }) {
  return <div className="overlay sign-in-overlay" onMouseDown={onClose}><section className="sign-in" onMouseDown={(event) => event.stopPropagation()}><button className="icon-button close-signin" onClick={onClose}><X /></button><span className="signin-icon"><LockKeyhole size={21} /></span><p className="signin-eyebrow">NETCAFE MANAGER</p><h2>Welcome back</h2><p>Sign in with your approved staff or administrator account.</p><label>Email<input autoFocus type="email" placeholder="your-email@gmail.com" id="login-email" /></label><label>Password<input type="password" placeholder="Enter your password" id="login-password" onKeyDown={(event) => event.key === "Enter" && onSubmit((document.getElementById("login-email") as HTMLInputElement).value, (event.target as HTMLInputElement).value)} /></label>{error && <div className="login-error">{error}</div>}<button onClick={() => onSubmit((document.getElementById("login-email") as HTMLInputElement).value, (document.getElementById("login-password") as HTMLInputElement).value)}>Sign in <ArrowRight size={17} /></button><small className="demo-logins">Use the email and password created through the administrator bootstrap or approval flow.</small></section></div>;
}
