"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Play, Square } from "lucide-react";
import { AppShell } from "./app-shell";
import { Landing, SignIn } from "./landing";
import { Modal } from "./modals";
import { AdminPage } from "./pages/admin-page";
import { CustomersPage } from "./pages/customers-page";
import { ProfilesPage } from "./pages/profiles-page";
import { ReportsPage } from "./pages/reports-page";
import { SettingsPage } from "./pages/settings-page";
import { StationsPage } from "./pages/stations-page";
import { Customer, PageId, Profile, Session, Station } from "./types";
import { apiFetch } from "@/lib/api";
import { supabase } from "@/lib/supabase/client";

export function NetCafeApp({ initialRole }: { initialRole?: "admin" | "staff" | "client" }) {
  const router = useRouter();
  const [signedIn, setSignedIn] = useState(false); const [showLogin, setShowLogin] = useState(false); const [loginError, setLoginError] = useState(""); const [page, setPage] = useState<PageId>("stations");
  const [profiles, setProfiles] = useState<Profile[]>([{ id: 1, firstName: "Izzy Kyle", middleName: "Abayabay", lastName: "Raganas", name: "Izzy Kyle Raganas", address: "Tipolo, Ubay, Bohol", contact: "09275834623", email: "izzy@netcafe.local", role: "Administrator", color: "#005463" }]);
  const [activeId, setActiveId] = useState<string | number>(1);
  const [stations, setStations] = useState<Station[]>([{ id: 1, name: "Computer 1", type: "Standard", rate: 3, active: false }, { id: 2, name: "PC 1", type: "VIP", rate: 3, active: false }]);
  const [customers, setCustomers] = useState<Customer[]>([]); const [sessions, setSessions] = useState<Session[]>([]);
  const [selected, setSelected] = useState<Station | null>(null); const [selectedCustomerId, setSelectedCustomerId] = useState(""); const [ending, setEnding] = useState<Station | null>(null);
  const [showAddStation, setShowAddStation] = useState(false); const [showAddCustomer, setShowAddCustomer] = useState(false); const [pendingRequests, setPendingRequests] = useState<Customer[]>([]);
  const active = profiles.find((item) => item.id === activeId) ?? profiles[0];
  const toProfile = (record: any): Profile => ({ id: record.id, userCode: record.user_code, firstName: record.first_name, middleName: record.middle_name ?? "", lastName: record.last_name, name: [record.first_name, record.middle_name, record.last_name].filter(Boolean).join(" "), address: record.address, contact: record.contact, email: record.email, role: record.role === "admin" ? "Administrator" : "Staff", color: record.role === "admin" ? "#005463" : "#123b61" });
  const toCustomer = (record: any): Customer => ({ id: record.id, userCode: record.user_code, name: [record.first_name, record.middle_name, record.last_name].filter(Boolean).join(" "), contact: record.contact, approved: ["approved", "active"].includes(String(record.status).toLowerCase()), balance: Number(record.balance ?? 0), totalSpent: Number(record.total_spent ?? 0), memberSince: new Date(record.created_at).toLocaleDateString() });
  const loadCustomers = async () => { const response = await apiFetch("/api/customers") as { customers: any[] }; setCustomers(response.customers.map(toCustomer)); };
  const syncOpenSessions = async () => {
    const response = await apiFetch("/api/station-sessions/open") as { sessions: any[] };
    const openByStation = new Map(response.sessions.map((session) => [String(session.station_key), session]));
    setStations((items) => items.map((station) => {
      const open = openByStation.get(String(station.id));
      return open ? { ...station, pending: open.status === "pending_client", active: open.status === "active", customer: open.customer_name, customerId: open.customer_profile_id, startedAt: open.started_at ? new Date(open.started_at).getTime() : undefined } : { ...station, pending: false, active: false, customer: undefined, customerId: undefined, startedAt: undefined };
    }));
  };
  useEffect(() => { if (!signedIn) return; void syncOpenSessions().catch(() => undefined); const refresh = window.setInterval(() => void syncOpenSessions().catch(() => undefined), 4000); return () => window.clearInterval(refresh); }, [signedIn]);
  useEffect(() => {
    if (initialRole === "client") {
      router.push("/client");
    } else if ((initialRole === "admin" || initialRole === "staff") && !signedIn) {
      setShowLogin(true);
    }
  }, [initialRole, signedIn, router]);
  const signIn = async (email: string, password: string) => { const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) return setLoginError(error.message); try { const response = await apiFetch("/api/me") as { profile: any }; const profile = toProfile(response.profile); if (response.profile.status !== "active") throw new Error("Your account is not active yet."); setProfiles([profile]); setActiveId(profile.id); await loadCustomers(); setLoginError(""); setShowLogin(false); setSignedIn(true); } catch (requestError) { await supabase.auth.signOut(); setLoginError(requestError instanceof Error ? requestError.message : "Unable to load your profile."); } };
  const start = async () => { if (!selected || !selectedCustomerId) return; try { const response = await apiFetch("/api/station-sessions", { method: "POST", body: JSON.stringify({ stationKey: String(selected.id), stationName: selected.name, hourlyRate: selected.rate, customerProfileId: selectedCustomerId }) }) as { session: any }; const customer = customers.find((item) => String(item.id) === selectedCustomerId); setStations((items) => items.map((item) => item.id === selected.id ? { ...item, pending: true, customer: customer?.name, customerId: selectedCustomerId } : item)); setSelected(null); setSelectedCustomerId(""); window.alert(`${response.session.customer_name} is assigned to ${selected.name}. The session will start when they sign in at /client.`); } catch (error) { window.alert(error instanceof Error ? error.message : "Could not create the waiting session."); } };
  const end = async () => { if (!ending) return; try { const response = await apiFetch(`/api/station-sessions/${ending.id}/end`, { method: "POST" }) as { session: any }; const saved = response.session; setSessions((items) => [{ id: Date.now(), station: saved.station_name, customer: saved.customer_name, startedAt: new Date(saved.started_at).getTime(), endedAt: new Date(saved.ended_at).getTime(), total: Number(saved.total), payment: "Cash" }, ...items]); setStations((items) => items.map((item) => item.id === ending.id ? { ...item, active: false, pending: false, customer: undefined, customerId: undefined, startedAt: undefined } : item)); setEnding(null); } catch (error) { window.alert(error instanceof Error ? error.message : "Could not end this session."); } };
  if (!signedIn) return <>{<Landing onSignIn={() => setShowLogin(true)} />}{showLogin && <SignIn error={loginError} onClose={() => setShowLogin(false)} onSubmit={signIn} />}</>;
  const approvedCustomers = customers.filter((customer) => customer.approved && typeof customer.id === "string");
  return <AppShell activeProfile={active} page={page} setPage={setPage} onSignOut={() => { void supabase.auth.signOut(); setPage("stations"); setSignedIn(false); }}>
    {page === "stations" && <StationsPage stations={stations} onStart={setSelected} onEnd={setEnding} onAdd={() => setShowAddStation(true)} />}
    {page === "customers" && <CustomersPage customers={customers} onAdd={() => setShowAddCustomer(true)} onTopUp={async (customer) => { const str = window.prompt(`Top up ${customer.name}'s balance (PHP):`, "100"); const amount = Number(str); if (amount > 0) { try { const res = await apiFetch(`/api/customers/${customer.id}/top-up`, { method: "POST", body: JSON.stringify({ amount }) }) as { profile: any }; setCustomers((items) => items.map((item) => item.id === customer.id ? { ...item, balance: Number(res.profile.balance) } : item)); window.alert(`Successfully topped up ₱${amount.toFixed(2)} to ${customer.name}. New balance: ₱${Number(res.profile.balance).toFixed(2)}`); } catch (err) { window.alert(err instanceof Error ? err.message : "Top-up failed"); } } }} onHistory={(customer) => { const count = sessions.filter((session) => session.customer === customer.name).length; window.alert(`${customer.name} has ${count} recorded session${count === 1 ? "" : "s"}.`); }} onEdit={(customer) => { const name = window.prompt("Customer name:", customer.name); const contact = window.prompt("Contact:", customer.contact); if (name?.trim()) setCustomers((items) => items.map((item) => item.id === customer.id ? { ...item, name: name.trim(), contact: contact?.trim() || item.contact } : item)); }} onDelete={async (customer) => { if (window.confirm(`Delete ${customer.name}? This cannot be undone.`)) { try { await apiFetch(`/api/admin/users/${customer.id}`, { method: "DELETE" }); setCustomers((items) => items.filter((item) => item.id !== customer.id)); } catch (err) { window.alert(err instanceof Error ? err.message : "Failed to delete customer"); } } }} />}
    {page === "reports" && <ReportsPage stations={stations} sessions={sessions} />}
    {page === "admin" && <AdminPage customers={customers} setCustomers={setCustomers} stations={stations} sessions={sessions} profiles={profiles} activeProfile={active} setProfiles={setProfiles} pendingRequests={pendingRequests} setPendingRequests={setPendingRequests} />}
    {page === "profiles" && <ProfilesPage profile={active} onSave={async (updatedProfile) => { const response = await apiFetch("/api/me/profile", { method: "PATCH", body: JSON.stringify({ firstName: updatedProfile.firstName, middleName: updatedProfile.middleName, lastName: updatedProfile.lastName, address: updatedProfile.address, contact: updatedProfile.contact }) }) as { profile: any }; const saved = toProfile(response.profile); setProfiles([saved]); setActiveId(saved.id); }} />}
    {page === "settings" && <SettingsPage stations={stations} />}
    {selected && <Modal title={`Assign Customer — ${selected.name}`} onClose={() => { setSelected(null); setSelectedCustomerId(""); }}><label>Registered customer<select autoFocus value={selectedCustomerId} onChange={(event) => setSelectedCustomerId(event.target.value)}><option value="">Choose a customer</option>{approvedCustomers.map((customer) => <option key={customer.id} value={customer.id}>{customer.userCode ? `${customer.userCode} — ` : ""}{customer.name}</option>)}</select></label><p className="rate-callout">The session will wait for the customer to sign in at <b>/client</b>. Billing begins only after their client registration.</p><div className="modal-actions"><button className="secondary" onClick={() => { setSelected(null); setSelectedCustomerId(""); }}>Cancel</button><button disabled={!selectedCustomerId} onClick={() => void start()}><Play size={17} /> Assign & Wait</button></div></Modal>}
    {ending && <Modal title={`End Session — ${ending.name}`} onClose={() => setEnding(null)}><div className="checkout-summary"><span>Customer <b>{ending.customer}</b></span><span>Rate <b>₱{ending.rate.toFixed(2)}/hr</b></span></div><div className="modal-actions"><button className="secondary" onClick={() => setEnding(null)}>Cancel</button><button className="danger" onClick={() => void end()}><Square size={17} /> End & Charge</button></div></Modal>}
    {showAddStation && <AddStation onClose={() => setShowAddStation(false)} onAdd={(name, type, rate, notes) => { setStations((items) => [...items, { id: Date.now(), name, type, rate, notes, active: false }]); setShowAddStation(false); }} />}
    {showAddCustomer && <AddCustomer onClose={() => setShowAddCustomer(false)} onAdd={async (firstName, middleName, lastName, address, contact, email, role, password) => { try { const response = await apiFetch("/api/account-requests", { method: "POST", body: JSON.stringify({ firstName, middleName, lastName, address, contact, email, role, password: role === "staff" ? password : undefined }) }) as { profile: any }; const name = [firstName, middleName, lastName].filter(Boolean).join(" "); const request: Customer = { id: response.profile.id, userCode: response.profile.user_code, name, contact, approved: false, balance: 0, totalSpent: 0, memberSince: new Date(response.profile.created_at).toLocaleDateString(), role }; if (role === "customer") setCustomers((items) => [...items, request]); setPendingRequests((items) => [...items, request]); setShowAddCustomer(false); } catch (error) { window.alert(error instanceof Error ? error.message : "Could not create account"); } }} />}
  </AppShell>;
}

function AddStation({ onClose, onAdd }: { onClose: () => void; onAdd: (name: string, type: Station["type"], rate: number, notes: string) => void }) { const [name, setName] = useState(""); const [type, setType] = useState<Station["type"]>("Standard"); const [rate, setRate] = useState("3"); const [notes, setNotes] = useState(""); return <Modal title="Add Station" onClose={onClose}><label>Name<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. PC-01" /></label><label>Type<select value={type} onChange={(event) => setType(event.target.value as Station["type"])}><option>Standard</option><option>VIP</option></select></label><label>Hourly Rate<input type="number" value={rate} onChange={(event) => setRate(event.target.value)} /></label><label>Notes<input value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="e.g. has headset" /></label><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button onClick={() => name && onAdd(name, type, Number(rate), notes)}>Add Station</button></div></Modal>; }
function AddCustomer({ onClose, onAdd }: { onClose: () => void; onAdd: (firstName: string, middleName: string, lastName: string, address: string, contact: string, email: string, role: "customer" | "staff", password: string) => void }) { const [firstName, setFirstName] = useState(""); const [middleName, setMiddleName] = useState(""); const [lastName, setLastName] = useState(""); const [address, setAddress] = useState(""); const [contact, setContact] = useState(""); const [email, setEmail] = useState(""); const [role, setRole] = useState<"customer" | "staff">("customer"); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const submit = () => { if (!firstName || !lastName || !address || !contact || !email) return; if (role === "staff" && password.length < 12) return window.alert("Staff passwords must be at least 12 characters."); if (role === "staff" && password !== confirmPassword) return window.alert("The staff passwords do not match."); onAdd(firstName, middleName, lastName, address, contact, email, role, password); }; return <Modal title="Create Account" onClose={onClose}><label>Account type<select value={role} onChange={(event) => setRole(event.target.value as "customer" | "staff")}><option value="customer">Customer</option><option value="staff">Staff</option></select></label><label>First name<input autoFocus value={firstName} onChange={(event) => setFirstName(event.target.value)} /></label><label>Middle name<input value={middleName} onChange={(event) => setMiddleName(event.target.value)} /></label><label>Last name<input value={lastName} onChange={(event) => setLastName(event.target.value)} /></label><label>Address<input value={address} onChange={(event) => setAddress(event.target.value)} /></label><label>Contact number<input value={contact} onChange={(event) => setContact(event.target.value)} /></label><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label>{role === "staff" && <><label>Staff password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="At least 12 characters" /></label><label>Confirm password<input type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} /></label></>}<p className="rate-callout">{role === "staff" ? "The staff account stays pending until the admin approves it. No email invitation will be sent." : "New customer accounts remain pending until an administrator approves them, then receive an invitation email."}</p><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button onClick={submit}>Create {role === "staff" ? "Staff" : "Customer"}</button></div></Modal>; }
